// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	AddressID int64       `json:"address_id"`
	Street    pgtype.Text `json:"street"`
	City      pgtype.Text `json:"city"`
	Planet    pgtype.Text `json:"planet"`
	Phone     string      `json:"phone"`
}

type Index struct {
	IndexID int64 `json:"index_id"`
}

type Student struct {
	ID             int32       `json:"id"`
	StudentID      int64       `json:"student_id"`
	FirstName      string      `json:"first_name"`
	LastName       string      `json:"last_name"`
	Age            pgtype.Int4 `json:"age"`
	Email          string      `json:"email"`
	Gender         pgtype.Text `json:"gender"`
	FavouriteColor pgtype.Text `json:"favourite_color"`
	StudentAddress int64       `json:"student_address"`
	CreatedAt      int64       `json:"created_at"`
	UpdatedAt      int64       `json:"updated_at"`
	Deleted        pgtype.Bool `json:"deleted"`
}
