// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: student.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIndex = `-- name: CreateIndex :one
INSERT INTO index (
        index_id)
VALUES ($1)
RETURNING index_id
`

func (q *Queries) CreateIndex(ctx context.Context, indexID int64) (int64, error) {
	row := q.db.QueryRow(ctx, createIndex, indexID)
	var index_id int64
	err := row.Scan(&index_id)
	return index_id, err
}

const createStudent = `-- name: CreateStudent :one
INSERT INTO students (
   student_id,first_name, last_name, age, email, gender, favourite_color, student_address, created_at, updated_at, deleted)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, student_id, first_name, last_name, age, email, gender, favourite_color, student_address, created_at, updated_at, deleted
`

type CreateStudentParams struct {
	StudentID      int64       `json:"student_id"`
	FirstName      string      `json:"first_name"`
	LastName       string      `json:"last_name"`
	Age            pgtype.Int4 `json:"age"`
	Email          string      `json:"email"`
	Gender         pgtype.Text `json:"gender"`
	FavouriteColor pgtype.Text `json:"favourite_color"`
	StudentAddress int64       `json:"student_address"`
	CreatedAt      int64       `json:"created_at"`
	UpdatedAt      int64       `json:"updated_at"`
	Deleted        pgtype.Bool `json:"deleted"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, createStudent,
		arg.StudentID,
		arg.FirstName,
		arg.LastName,
		arg.Age,
		arg.Email,
		arg.Gender,
		arg.FavouriteColor,
		arg.StudentAddress,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Deleted,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.FirstName,
		&i.LastName,
		&i.Age,
		&i.Email,
		&i.Gender,
		&i.FavouriteColor,
		&i.StudentAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Deleted,
	)
	return i, err
}

const createStudentAddress = `-- name: CreateStudentAddress :one
INSERT INTO address
(address_id, street, city, planet, phone)
VALUES ($1, $2, $3, $4, $5)
RETURNING address_id, street, city, planet, phone
`

type CreateStudentAddressParams struct {
	AddressID int64       `json:"address_id"`
	Street    pgtype.Text `json:"street"`
	City      pgtype.Text `json:"city"`
	Planet    pgtype.Text `json:"planet"`
	Phone     string      `json:"phone"`
}

func (q *Queries) CreateStudentAddress(ctx context.Context, arg CreateStudentAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, createStudentAddress,
		arg.AddressID,
		arg.Street,
		arg.City,
		arg.Planet,
		arg.Phone,
	)
	var i Address
	err := row.Scan(
		&i.AddressID,
		&i.Street,
		&i.City,
		&i.Planet,
		&i.Phone,
	)
	return i, err
}

const deleteStudent = `-- name: DeleteStudent :exec
UPDATE students
SET deleted = true
WHERE id = $1 AND deleted = false
`

func (q *Queries) DeleteStudent(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteStudent, id)
	return err
}

const deleteStudentAddress = `-- name: DeleteStudentAddress :exec
DELETE FROM address
WHERE address_id = $1
`

func (q *Queries) DeleteStudentAddress(ctx context.Context, addressID int64) error {
	_, err := q.db.Exec(ctx, deleteStudentAddress, addressID)
	return err
}

const getIndexes = `-- name: GetIndexes :one
SELECT index_id FROM index
ORDER BY index_id
`

func (q *Queries) GetIndexes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getIndexes)
	var index_id int64
	err := row.Scan(&index_id)
	return index_id, err
}

const getStudent = `-- name: GetStudent :one
SELECT id, student_id, first_name, last_name, age, email, gender, favourite_color, student_address, created_at, updated_at, deleted FROM students
WHERE id = $1 AND deleted = false
`

func (q *Queries) GetStudent(ctx context.Context, id int32) (Student, error) {
	row := q.db.QueryRow(ctx, getStudent, id)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.FirstName,
		&i.LastName,
		&i.Age,
		&i.Email,
		&i.Gender,
		&i.FavouriteColor,
		&i.StudentAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Deleted,
	)
	return i, err
}

const getStudentAddressOne = `-- name: GetStudentAddressOne :one
SELECT address_id, street, city, planet, phone FROM address
WHERE address_id = $1
`

func (q *Queries) GetStudentAddressOne(ctx context.Context, addressID int64) (Address, error) {
	row := q.db.QueryRow(ctx, getStudentAddressOne, addressID)
	var i Address
	err := row.Scan(
		&i.AddressID,
		&i.Street,
		&i.City,
		&i.Planet,
		&i.Phone,
	)
	return i, err
}

const getStudentAddresses = `-- name: GetStudentAddresses :many
SELECT address_id, street, city, planet, phone FROM address
ORDER BY address_id
LIMIT $1 OFFSET $2
`

type GetStudentAddressesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetStudentAddresses(ctx context.Context, arg GetStudentAddressesParams) ([]Address, error) {
	rows, err := q.db.Query(ctx, getStudentAddresses, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Address
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.AddressID,
			&i.Street,
			&i.City,
			&i.Planet,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudents = `-- name: ListStudents :many
SELECT id, student_id, first_name, last_name, age, email, gender, favourite_color, student_address, created_at, updated_at, deleted FROM students
WHERE deleted = false
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListStudentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListStudents(ctx context.Context, arg ListStudentsParams) ([]Student, error) {
	rows, err := q.db.Query(ctx, listStudents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.FirstName,
			&i.LastName,
			&i.Age,
			&i.Email,
			&i.Gender,
			&i.FavouriteColor,
			&i.StudentAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIndex = `-- name: UpdateIndex :exec
UPDATE index
SET index_id = $2
WHERE index_id = $1
`

type UpdateIndexParams struct {
	IndexID   int64 `json:"index_id"`
	IndexID_2 int64 `json:"index_id_2"`
}

func (q *Queries) UpdateIndex(ctx context.Context, arg UpdateIndexParams) error {
	_, err := q.db.Exec(ctx, updateIndex, arg.IndexID, arg.IndexID_2)
	return err
}

const updateStudent = `-- name: UpdateStudent :exec
UPDATE students
SET first_name = $2, last_name = $3, age = $4 , email = $5, updated_at = $6
WHERE id = $1 AND deleted = false
`

type UpdateStudentParams struct {
	ID        int32       `json:"id"`
	FirstName string      `json:"first_name"`
	LastName  string      `json:"last_name"`
	Age       pgtype.Int4 `json:"age"`
	Email     string      `json:"email"`
	UpdatedAt int64       `json:"updated_at"`
}

func (q *Queries) UpdateStudent(ctx context.Context, arg UpdateStudentParams) error {
	_, err := q.db.Exec(ctx, updateStudent,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Age,
		arg.Email,
		arg.UpdatedAt,
	)
	return err
}
